### ISSUE TITLE
Visualizing risks

### ISSUE THREAD

**Issue by veeral-patel** [Netflix-Skunkworks/riskquant#14]
What are some visualizations that are commonly used in order to represent risks?

The loss exceedance curve is one and risk matrices are another:

![](https://www.industrysafe.com/hs-fs/hubfs/Stock%20images/3x3%20risk%20matrix.jpg?width=652&name=3x3%20risk%20matrix.jpg)

What else is used? Or, is there a book/blog post/existing tool/another resource you suggest I check out to answer this question?

**Comment by snkilmartin** [comment]
To start this problem, Markus and I both read [How to Measure Anything in Cybersecurity Risk](https://www.howtomeasureanything.com/cybersecurity/) and found it very helpful!

Chapter 3 has a good section on visualizing risk;  loss exceedance and risk tolerance curves are recommended.

Chapter 5 of this book talks through many of the issues with risk matrices.  Risk matrices are qualitative and are not recommended in the book.
