### ISSUE TITLE
ModuleNotFoundError: No module named 'riskquant.model'

### ISSUE THREAD

**Issue by confusedcrib** [Netflix-Skunkworks/riskquant#21]
Hey all. When trying to run via the CLI and/or Docker by bringing my own CSV I get the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/riskquant", line 5, in <module>
    import riskquant
  File "/usr/local/lib/python3.7/site-packages/riskquant/__init__.py", line 23, in <module>
    from riskquant import simpleloss
  File "/usr/local/lib/python3.7/site-packages/riskquant/simpleloss.py", line 30, in <module>
    from riskquant.model import lognormal_magnitude, poisson_frequency
ModuleNotFoundError: No module named 'riskquant.model'
```

This occurs when trying to run riskquant --file input.csv after a pip install and when trying to run riskquant after docker run -it /bin/bash.

If I try the docker command I get:

```
riskquant % docker container run --rm -it \
  -v "$(PWD)/data/":/data/ \
  riskquant --file /data/input.csv
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"--file\": executable file not found in $PATH": unknown.
```

**Comment by pmesposito** [comment]
Hi, I also got the first error. The installation only copies the files in the main folder, and not the files in the "model" folder. To solve this, copy the model folder to your package's folder (/usr/local/lib/python3.7/site-packages/riskquant).

**Comment by confusedcrib** [comment]
Unfortunately 'm still getting the issue after copying /riskquant/model/, have you gotten a dockerfile change to work? Just want to make sure my local python install isn't the issue.

**Comment by pmesposito** [comment]
I didn't use docker.

**Comment by confusedcrib** [comment]
Thank you! I was actually able to get it working after doing the copy
