### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by blackfist** [Netflix-Skunkworks/riskquant#3]
I'd be interested in working on a PR to add some functionality to the SimpleLoss class but I wanted to get an opinion from the maintainers first. For one thing, I'd like to know if you're allowed to accept contributions from persons outside of Netflix and if there is a release I would need to sign or anything like that. I'd also like to know how you would like to receive contributions - just fork the repo and issue a pull request?

**Comment by snkilmartin** [comment]
Hey, we do accept contributions outside of Netflix for riskquant, thanks so much for your interest!  A PR is great... I still need to set up travis ci to automate tests, so for now I'll just verify the PR, making sure the tests pass and that we have coverage.

**Comment by snkilmartin** [comment]
I went with the github pythonapp workflow instead of travis ci, so feel free to submit a PR whenever you have time
