### ISSUE TITLE
AssertionError when Frequency greater than 1

### ISSUE THREAD

**Issue by bdooling** [Netflix-Skunkworks/riskquant#9]
For a risk scenario that is forecasted to occur more than once per time interval (e.g. three times per year), we assign a frequency of > 1.0. However this causes an error in simpleloss:

 
> from riskquant import simpleloss
> s = simpleloss.SimpleLoss(label="ALICE", name="Alice steals the data", p=0.10, low_loss=100000, high_loss=1000000)
> s.annualized_loss()
40400.12826945729

> s = simpleloss.SimpleLoss(label="ALICE", name="Alice steals the data", p=3.10, low_loss=100000, high_loss=1000000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/riskquant/riskquant/simpleloss.py", line 40, in __init__
    raise AssertionError
AssertionError

Is this expected / intended? 

If so, is the recommendation to forecast occurrence over a shorter time interval (e.g. month), then extrapolate outside of riskquant? (x12 to arrive at an annual figure)

**Comment by mdeshon** [comment]
You're seeing an artifact of my evolving understanding of risk quantification--initially I thought these were probabilities, but later realized they are frequencies instead. Unfortunately, I didn't remove that assertion.

I'll fix it and get the improved version up soon. In the meantime, you can workaround the problem by commenting out that if/assert statement, the code should still work and give good results, but I'll test it all to make sure before I create a new PR.

**Comment by bdooling** [comment]
Thanks for the quick response @mdeshon ! 

That workaround should do just fine for my purposes. 

Thanks for your work on this project!

**Comment by snkilmartin** [comment]
I just merged the PR from @mdeshon that resolves this
